/* various defines */

#define MINC2 @MINC2@
#define PACKAGE_NAME "@PACKAGE_NAME@"
#define PACKAGE_BUGREPORT "@PACKAGE_BUGREPORT@"
#define PACKAGE_VERSION "@PACKAGE_VERSION@"
#define PACKAGE_STRING "@PACKAGE_STRING@"

#define VERSION PACKAGE_VERSION

#define HAVE_MKSTEMP @HAVE_MKSTEMP@
#define HAVE_STRERROR @HAVE_STRERROR@
