#! /bin/csh -f

set path = (/usr/sbin /usr/bsd /sbin /usr/bin /bin /usr/local/bin)

if ($#argv != 1) then
   exit -1
endif

gzip $1 < /dev/null > /dev/null

if ($status) exit $status

ls -t $1* |head -1
