# --------------------------------------------------------------------
#
# MINC Makefile
#

ROOT = ../..
include $(ROOT)/Make_machine_specific
include $(ROOT)/Make_configuration

# Executable names
SCRIPTS  = mincheader
MANSECT  = 1
MANPAGES = $(SCRIPTS).$(MANSECT)

include $(ROOT)/progs/Make_scripts

