#! /bin/csh -f

# Check arguments

if ($#argv != 1) then
   echo "Usage: $0 <minc file>
   exit
endif
set file = $1

# Get variables names (excluding image): remove leading "image", remove word 
# "image", collapse multiple blanks to one, remove leading blanks, remove
# trailing blanks, replace blanks with commas
set vars = `mincinfo -varnames $file | sed -e 's/^image //g' -e 's/ image / /g' -e 's/  */ /g' -e 's/^ //' -e 's/ $//' -e 's/ /,/g'`

ncdump -v "$vars" $1
