# --------------------------------------------------------------------
#
# MINC Makefile
#

ROOT = ../..
include $(ROOT)/Makefile_machine_specific
include $(ROOT)/Makefile_configuration

# Executable names
PROGS    = mincedit

# --------------------------------------------------------------------

default: all

all:
	echo $(PROGS) is up to date
