# --------------------------------------------------------------------
#
# MINC Makefile
#

ROOT = ../..
include $(ROOT)/Make_machine_specific
include $(ROOT)/Make_configuration

# Executable names
SCRIPTS    = mincdiff

include $(ROOT)/progs/Make_scripts

