      SUBROUTINE MIAGT(CDFID, VARID, ATTNAME, DATATYPE, MAX_LENGTH, 
     +                 VALUE, ATT_LENGTH,RCODE)
      SUBROUTINE MIAGT1(CDFID, VARID, ATTNAME, DATATYPE, VALUE, RCODE)
      SUBROUTINE MIVGT(CDFID, VARID, START, COUNT, DATATYPE, DATASIGN,
     +                 VALUE, RCODE)
      SUBROUTINE MIVGT1(CDFID, VARID, INDICES, DATATYPE, DATASIGN,
     +                  VALUE, RCODE)
      SUBROUTINE MIVPT(CDFID, VARID, START, COUNT, DATATYPE, DATASIGN,
     +                 VALUE, RCODE)
      SUBROUTINE MIVPT1(CDFID, VARID, INDICES, DATATYPE, DATASIGN,
     +                  VALUE, RCODE)
      SUBROUTINE MISTCD(NVALS, IVALUE, COORDS, RCODE)
      SUBROUTINE MITRCD(CDFID, INVARID, INCOORDS, OUTVARID, OUTCOORDS,
     +                  RCODE)
      SUBROUTINE MICAAT(INCDFID, INVARID, OUTCDFID, OUTVARID, RCODE)
      INTEGER FUNCTION MICVD(INCDFID, INVARID, OUTCDFID, RCODE)
      SUBROUTINE MICVV(INCDFID, INVARID, OUTCDFID, OUTVARID, RCODE)
      SUBROUTINE MICAVD(INCDFID, OUTCDFID, NEXCLUDE, EXCLUDED_VARS,
     +                  RCODE)
      SUBROUTINE MICAVV(INCDFID, OUTCDFID, NEXCLUDE, EXCLUDED_VARS,
     +                  RCODE)
      SUBROUTINE MIAPTP(CDFID, VARID, ATTNAME, PTRVARID, RCODE)
      INTEGER FUNCTION MIAGTP(CDFID, VARID, ATTNAME, RCODE)
      SUBROUTINE MICHLD(CDFID, PARENT_VARID, CHILD_VARID, RCODE)
      INTEGER FUNCTION MISTDV(CDFID, VARNAME, DATATYPE, NDIMS, 
     +                        DIMARRAY, RCODE)
      INTEGER FUNCTION MIGRPV(CDFID, VARNAME, RCODE)

      INTEGER FUNCTION ICVCRT(RCODE)
      SUBROUTINE ICVFRE(ICVID, RCODE)
      SUBROUTINE ICVSTD(ICVID, ICV_PROPERTY, DVALUE, RCODE)
      SUBROUTINE ICVSTI(ICVID, ICV_PROPERTY, IVALUE, RCODE)
      SUBROUTINE ICVSTS(ICVID, ICV_PROPERTY, SVALUE, LENSTR, RCODE)
      SUBROUTINE ICVNQD(ICVID, ICV_PROPERTY, DVALUE, RCODE)
      SUBROUTINE ICVNQI(ICVID, ICV_PROPERTY, IVALUE, RCODE)
      SUBROUTINE ICVNQS(ICVID, ICV_PROPERTY, SVALUE, LENSTR, RCODE)
      SUBROUTINE ICVATT(ICVID, CDFID, VARID, RCODE)
      SUBROUTINE ICVNDA(ICVID, CDFID, VARID, RCODE)
      SUBROUTINE ICVDET(ICVID, RCODE)
      SUBROUTINE ICVGET(ICVID, START, COUNT, VALUE, RCODE)
      SUBROUTINE ICVPUT(ICVID, START, COUNT, VALUE, RCODE)

C
C     VARIABLE DECLARATIONS
C
      INTEGER CDFID
      INTEGER VARID
      CHARACTER*(*) ATTNAME
      INTEGER DATATYPE
      INTEGER MAX_LENGTH
      DOUBLE PRECISION VALUE
      REAL VALUE
      INTEGER VALUE
      INTEGER RCODE
      INTEGER START(*)
      INTEGER COUNT(*)
      CHARACTER*(*) DATASIGN
      INTEGER INDICES(*)
      INTEGER NVALS
      INTEGER IVALUE
      INTEGER COORDS(*)
      INTEGER INVARID
      INTEGER INCOORDS(*)
      INTEGER OUTVARID
      INTEGER OUTCOORDS(*)
      INTEGER INCDFID
      INTEGER OUTCDFID
      INTEGER NEXCLUDE
      INTEGER EXCLUDED_VARS(NEXCLUDE)
      INTEGER PTRVARID
      INTEGER PARENT_VARID
      INTEGER CHILD_VARID
      CHARACTER*(*) VARNAME
      INTEGER NDIMS
      INTEGER DIMARRAY(NDIMS)
      INTEGER ICVID
      INTEGER ICV_PROPERTY
      DOUBLE PRECISION DVALUE
      INTEGER IVALUE
      CHARACTER*(*) SVALUE
      INTEGER LENSTR
      
